[package]
name = "internal_proc_macros"
version = "0.0.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1"
syn = { version = "2", features = ["full"] }
quote = "1"
paste = "1"
internal_shared = { path = "../internal_shared" }
lazy_static = "1.5.0"
